[2025-09-16T10:31:30.669+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag1_test_production_summary.create_test_production_summary manual__2025-09-16T10:31:27.990529+00:00 [queued]>
[2025-09-16T10:31:30.674+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag1_test_production_summary.create_test_production_summary manual__2025-09-16T10:31:27.990529+00:00 [queued]>
[2025-09-16T10:31:30.675+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-09-16T10:31:30.683+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): create_test_production_summary> on 2025-09-16 10:31:27.990529+00:00
[2025-09-16T10:31:30.687+0000] {standard_task_runner.py:60} INFO - Started process 539 to run task
[2025-09-16T10:31:30.690+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag1_test_production_summary', 'create_test_production_summary', 'manual__2025-09-16T10:31:27.990529+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/sql_flow.py', '--cfg-path', '/tmp/tmp429n1vdj']
[2025-09-16T10:31:30.693+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask create_test_production_summary
[2025-09-16T10:31:30.730+0000] {task_command.py:423} INFO - Running <TaskInstance: dag1_test_production_summary.create_test_production_summary manual__2025-09-16T10:31:27.990529+00:00 [running]> on host fc138b05e570
[2025-09-16T10:31:30.779+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag1_test_production_summary' AIRFLOW_CTX_TASK_ID='create_test_production_summary' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T10:31:27.990529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T10:31:27.990529+00:00'
[2025-09-16T10:31:30.845+0000] {logging_mixin.py:188} INFO - Error: relation "production_journal" does not exist
LINE 9:         FROM Production_Journal pj
                     ^
[2025-09-16T10:31:30.846+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-09-16T10:31:30.852+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag1_test_production_summary, task_id=create_test_production_summary, execution_date=20250916T103127, start_date=20250916T103130, end_date=20250916T103130
[2025-09-16T10:31:30.903+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-09-16T10:31:30.916+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
